apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: streamlit-test-cluster
  region: us-west-2
  version: "1.27"

vpc:
  cidr: 10.0.0.0/16
  nat:
    gateway: Single

managedNodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        cloudWatch: true

addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest